### ISSUE TITLE
Improper handling of characters vs bytes

### ISSUE THREAD

**Issue by udoprog** [kieraneglin/lt#2]
Hey,

I noticed that you use `String#len()` to calculate the width of the column. This returns the length of the string in bytes, which doesn't always match the number of columns in the terminal.

Example with a character that renders as one column (notice that the padding is off-by-one):
```bash
$ mkdir empty
$ cd empty
$ mkdir Åfoobarbaz
$ cargo run
┌──────────────┬──────────┐
│ Filename     │ Filesize │
├──────────────┼──────────┤
│ Åfoobarbaz/  │    4,096 │
└──────────────┴──────────┘
```

Example with a character that renders as two columns:
```bash
$ mkdir empty
$ cd empty
$ mkdir 仈foobarbaz
$ cargo run
┌───────────────┬──────────┐
│ Filename      │ Filesize │
├───────────────┼──────────┤
│ 仈foobarbaz/   │    4,096 │
└───────────────┴──────────┘
```

The correct way would be to count the number of characters, and somehow determine how many terminal columns they will occupy. This gets a bit more interesting when considering that users might have different locales and/or terminal capabilities. But this might not be something you want to dig into just yet.

**Comment by mbrubeck** [comment]
You can use the [unicode-width] crate to determine the width in columns of an arbitrary Unicode string.  This takes into account zero-width and double-width characters, as well as the usual things like multi-byte code points.  (It's still not perfect because the actual displayed width can also depend on the display font and other factors, but it should handle the vast majority of cases correctly.)

[unicode-width]: https://crates.io/crates/unicode-width

**Comment by kieraneglin** [comment]
Thanks for the heads up, @mbrubeck!  This should be fixed now.
